version: "3.9"
services:
  redis:
    container_name: 'redis'
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
      - 8001:8001
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  webserver:
    image: yeaung276/nst
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_OM_URL=redis://redis:6379
    ports:
      - 8000:8000
